char-conv
plotnikov01/c-practice pull request #7
Opened 2023-12-13 15:08 UTC by plotnikov01

2023-12-13 15:28 UTC, MLGMAG requested changes

2023-12-13 15:28 UTC, MLGMAG commented on src/char_conv.c
> +		printf("Ascii value is %d \n", string[i]);
Extract `string[i]` into separate variable.

2023-12-13 15:28 UTC, MLGMAG commented on src/char_conv.c
> +	while(string[i] != '\0') {
Extract `\0` into constant

2023-12-13 15:28 UTC, MLGMAG commented on src/char_conv.c
> +int main()
Change to `int main() {`

2023-12-13 15:29 UTC, MLGMAG commented
Commit message should be: `[topic] description`

Change commit message to `[CharConversion] Implement logic`

2024-01-07 21:00 UTC, MLGMAG requested changes

2024-01-07 21:01 UTC, MLGMAG commented on src/char_conv.c
> +		printf("Ascii value is %d \n", string[i]);
Still present

2024-01-08 10:31 UTC, plotnikov01 commented on src/char_conv.c
> +		printf("Ascii value is %d \n", string[i]);
done

2024-01-08 11:48 UTC, MLGMAG approved these changes

2024-01-08 12:09 UTC, merged